// Auto-generated by @cerios/openapi-to-zod
// Do not edit this file manually

import { z } from "zod";

// Schemas and Types
export const slotsUserSchema = z.strictObject({
  /** Имя пользователя @example "Данек" */
  name: z.string(),
  /** Слоты, выбранные пользователем в формате UTC+0. В случае если встреча состоит из одного слота, то время начала совпадает со временем конца @example [["2026-12-21Т22:00:00Z","2026-12-22Т02:00:00Z"],["2026-12-22Т22:00:00Z","2026-12-23Т02:00:00Z"]] */
  slots: z.array(z.tuple([z.iso.datetime(), z.iso.datetime()])),
});
export type SlotsUser = z.infer<typeof slotsUserSchema>;

export const meetResponseSchema = z.strictObject({
  /** Название встречи @example "Встреча" */
  name: z.string(),
  /** Описание встречи @example "Описание встречи" */
  description: z.string().nullable().optional(),
  /** Прикрепленная к встрече ссылка @example "https://telemost.360.yandex.ru/j/6694975853" */
  link: z.string().nullable().optional(),
  /** Продолжительность встречи @example "01:30" */
  duration: z
    .string()
    .regex(/^(0[1-5]):([0-5][0-9])$/)
    .nullable()
    .optional(),
  /** Все слоты для встречи в формате UTC+0. Совпадать не могут. @example [["2026-12-21T22:00:00Z","2026-12-22T02:00:00Z"],["2026-12-22T22:00:00Z","2026-12-23T02:00:00Z"],["2026-12-24T22:00:00Z","2026-12-25T02:00:00Z"]] */
  timeRange: z.array(z.tuple([z.iso.datetime(), z.iso.datetime()])),
  /** Идентификатор встречи @example "f47ac10b-58cc-4372-a567-0e02b2c3d479" */
  hash: z.uuid(),
  /** Слоты, выбранные пользователями в формате UTC+0. В случае если встреча состоит из одного слота, то время начала совпадает со временем конца @example [{"Данек":[["2026-12-21Т22:00:00Z","2026-12-22Т02:00:00Z"],["2026-12-22Т22:00:00Z","2026-12-23Т02:00:00Z"]]},{"Кирилл":[["2026-12-21Т22:00:00Z","2026-12-21Т23:00:00Z"],["2026-12-23Т00:00:00Z","2026-12-23Т01:00:00Z"]]},{"Колян":[["2026-12-25Т00:00:00Z","2026-12-25Т00:00:00Z"]]}] */
  slots: z.array(slotsUserSchema),
});
export type MeetResponse = z.infer<typeof meetResponseSchema>;

export const meetCreateSchema = z.strictObject({
  /** Название встречи @example "Встреча" */
  name: z.string(),
  /** Описание встречи @example "Описание встречи" */
  description: z.string().nullable().optional(),
  /** Прикрепленная к встрече ссылка @example "https://telemost.360.yandex.ru/j/6694975853" */
  link: z.string().nullable().optional(),
  /** Продолжительность встречи @example "01:30" */
  duration: z
    .string()
    .regex(/^(0[1-5]):([0-5][0-9])$/)
    .nullable()
    .optional(),
  /** Все слоты для встречи в формате UTC+0. Совпадать не могут. @example [["2026-12-21Т22:00:00Z","2026-12-22Т02:00:00Z"],["2026-12-22Т22:00:00Z","2026-12-23Т02:00:00Z"],["2026-12-24Т22:00:00Z","2026-12-25Т02:00:00Z"]] */
  timeRange: z.array(z.array(z.iso.datetime())),
});
export type MeetCreate = z.infer<typeof meetCreateSchema>;

export const errorSchema = z.strictObject({
  /** @example "Something went wrong" */
  message: z.string(),
});
export type Error = z.infer<typeof errorSchema>;
