name: Deploy Preprod
run-name: "Build and Deploy PreProd"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    env:
      Y_TOKEN: ${{ secrets.Y_TOKEN }}
      REGISTRY: cr.yandex/${{ secrets.CONTAINER_REGISTRY }}
      IMAGE_TAG: ${{ github.sha }}
      DOMAIN: termeet-dev.ru
      EMAIL: ${{ secrets.EMAIL }}
      BACKEND_PORT: 8000
      BACKEND_HOST: backend.termeet-dev.ru
      BACKEND_CONTAINER: backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        run: |
          echo "${Y_TOKEN}" | docker login \
            --username oauth \
            --password-stdin \
            cr.yandex

      - name: Build Docker image
        run: |
          docker build \
            -f infra/Dockerfile \
            -t ${REGISTRY}/frontend:${IMAGE_TAG} \
            -t ${REGISTRY}/frontend:latest .

      - name: Push Docker images
        run: |
          docker push ${REGISTRY}/frontend:${IMAGE_TAG}
          docker push ${REGISTRY}/frontend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: Y_TOKEN,REGISTRY,IMAGE_TAG,DOMAIN,EMAIL,BACKEND_PORT,BACKEND_HOST,BACKEND_CONTAINER
          script: |
            echo "${Y_TOKEN}" | docker login \
              --username oauth \
              --password-stdin \
              cr.yandex
            
            docker pull ${REGISTRY}/frontend:${IMAGE_TAG}
            
            # Останавливаем старый frontend (preprod)
            docker stop frontend 2>/dev/null || true
            docker rm frontend 2>/dev/null || true
            
            # Запускаем новый frontend для preprod
            docker run -d \
              --name frontend \
              -e BACKEND_HOST=${BACKEND_HOST} \
              -e BACKEND_CONTAINER=${BACKEND_CONTAINER} \
              -e BACKEND_PORT=${BACKEND_PORT} \
              -e VIRTUAL_HOST=${DOMAIN} \
              -e LETSENCRYPT_EMAIL=${EMAIL} \
              -e LETSENCRYPT_HOST=${DOMAIN} \
              --network nginx-proxy \
              --restart unless-stopped \
              ${REGISTRY}/frontend:${IMAGE_TAG}
            
            docker image prune -f